#!/usr/bin/env bash
# Emit the LaTeX rows of Appendix "AI Tool Use" from the repository's own git
# history, so the disclosure table is regenerable rather than remembered.
#
#   bash code/list_ai_assisted.sh              # print the rows
#   bash code/list_ai_assisted.sh --list       # print path/status/source, no LaTeX
#
# MEMBERSHIP AND STATUS COME FROM GIT, NOT FROM A LIST KEPT BY HAND.
# A file is in the table if it differs from BASE, whether that difference is
# committed or still in the working tree, and it is "new" exactly when it did
# not exist at BASE.
#
# BASE is the last commit before the revision round. 713bfd3 is the first
# commit that creates results/revision/ and its own message opens the round, so
# its parent is the boundary. Commits before BASE built the original pipeline
# and had no AI involvement; widen BASE only if that stops being true.
BASE="${AI_DISCLOSURE_BASE:-9cbbbed}"
DIRS=(code colab reproduction)

set -u
cd "$(dirname "$0")/.."

if ! git rev-parse --verify --quiet "$BASE^{commit}" >/dev/null; then
  echo "list_ai_assisted: BASE $BASE is not a commit in this repository" >&2
  exit 2
fi

# committed since BASE, uncommitted against HEAD, and never-added files
{
  git diff --name-only "$BASE" HEAD -- "${DIRS[@]}"
  git diff --name-only HEAD -- "${DIRS[@]}"
  git ls-files --others --exclude-standard -- "${DIRS[@]}"
} | sed 's#\\#/#g' | sort -u | grep -vE '(^|/)(__pycache__|\.ipynb_checkpoints)/' \
  | grep -vE '\.(pyc|zip)$' > /tmp/.ai_paths.$$

BASE="$BASE" LISTONLY="${1:-}" python - /tmp/.ai_paths.$$ <<'PY'
import json
import os
import re
import subprocess
import sys

BASE = os.environ["BASE"]
LISTONLY = os.environ.get("LISTONLY", "") == "--list"
paths = [l.strip() for l in open(sys.argv[1]) if l.strip()]

# A file that changed but has no stated change is a hole in a compliance
# disclosure, so the script fails loudly rather than emitting a short table.
# Keys are repository paths. Values are the one-line statement of the change.
MODIFIED = {
    "code/paper_pipeline/experiments/e2_hgt.py":
        "added build_graph_v2 with the strict, f1a, f1b and strict_lineage "
        "contracts; the frozen build_graph is left byte for byte",
    "code/paper_pipeline/utils/data.py":
        "build_features fits TF-IDF on the training split; tfidf_legacy keeps "
        "the frozen all-rows path (finding W5)",
    "code/paper_pipeline/experiments/e14_self_persistence.py":
        "same W5 repair in student_tfidf, the second instance of the finding",
    "code/make_e12_manifest.py":
        "the manifest declares all five edge types the graph builds, not "
        "three (finding F7)",
    "code/r3_rgcn_symmetric.py":
        "train_eval generalized to RGCN, GAT and HGT behind a structural "
        "architecture guard; attach_t0_norm added",
    "reproduction/reproduce_assertions.py":
        "added the revision-layer and supplement checks and the skip "
        "accounting, 26 checks to 74",
    "colab/t2_1_strict_contract.ipynb":
        "regenerated by r26 as the strict-contract notebook",
}

# Descriptions for new files that carry no python docstring.
NEW_NONPY = {
    "colab/t2_1_strict_contract.ipynb":
        "Colab notebook for the strict-contract graph rerun, emitted by r26",
    "colab/t2_2b_lineage_tabpfn.ipynb":
        "Colab notebook for the lineage arm and the full-context TabPFN rung, "
        "emitted by r34",
    "code/run_b1_titles_abstracts.sh":
        "detached launcher for the title and abstract fetch, then its merge",
    "code/run_b2_time_contract.sh":
        "detached launcher for the concept event tables, then the "
        "time-contract verifier",
    "code/list_ai_assisted.sh":
        "emits the rows of this table from git history",
    "reproduction/submission_template.json":
        "the documented submission format the validator accepts",
}

# New files whose content is substantially derived from a pre-existing file.
# Recorded so the table cannot imply they were written from nothing.
DERIVED = {
    "code/r25_strict_contract.py": "code/r3_rgcn_symmetric.py",
    "code/r26_make_t2_1_bundle.py": "colab/make_gnn_notebook.py",
    "code/r31_lineage_table.py": "code/r23_genealogy_tabular.py",
    "code/r32_lineage_contract.py": "code/r25_strict_contract.py",
    "code/r33_tabpfn_gpu.py":
        "code/paper_pipeline/experiments/r15_tabpfn_standalone.py",
    "code/r34_make_lineage_bundle.py": "code/r26_make_t2_1_bundle.py",
    "code/r35_fetch_titles_abstracts.py": "code/r5_fetch_author_works.py",
    "code/r36_concept_events.py": "code/r5_fetch_author_works.py",
    "code/r39_emit_mech_appendix.py": "code/r29_emit_strict_appendix.py",
    "code/r37_emit_table4.py": "code/r29_emit_strict_appendix.py",
    # these two say so themselves, in a docstring naming the source as verbatim
    "code/r_eval_util.py": "code/paper_pipeline/experiments/r11_power_tost.py",
    "code/r38_t33_mechanism.py":
        "code/paper_pipeline/experiments/e9a_placebo.py",
    "reproduction/verify_time_contract.py": "code/build_neuro_dataset.py",
    "reproduction/validate_submission.py": "code/e12_corrected_aggregation.py",
}


def existed_at_base(p):
    return subprocess.run(["git", "cat-file", "-e", f"{BASE}:{p}"],
                          capture_output=True).returncode == 0


def docline(p):
    """First sentence of a python module docstring, which states what the file
    is. Read from the file rather than recalled."""
    try:
        src = open(p, encoding="utf-8").read()
    except OSError:
        return None
    # [^\n]* for the shebang, not .*: re.S makes . match newlines, and a
    # greedy .* walks past the real docstring to some later triple quote.
    # The optional [rRbBuUfF] prefix matters: r44_escape_scan.py must use a raw
    # docstring, because its text contains literal backslash-r and backslash-n
    # sequences. Without the prefix here the guard reports it as undocumented.
    m = re.search(r'^\s*(?:#![^\n]*\n)?[rRbBuUfF]{0,2}(?:"""|\'\'\')(.*?)(?:"""|\'\'\')',
                  src, re.S)
    if not m:
        return None
    body = m.group(1).strip()
    first = body.split("\n\n")[0].replace("\n", " ").strip()
    first = re.sub(r"\s+", " ", first)
    # one line means one sentence; the rest of the docstring is the file's own
    sent = re.split(r"(?<=[a-z0-9\)])\.\s+", first)[0]
    return sent.rstrip(".") or None


def esc(s):
    return (s.replace("\\", r"\textbackslash{}").replace("_", r"\_")
             .replace("&", r"\&").replace("%", r"\%").replace("#", r"\#"))


rows, missing = [], []
for p in paths:
    if not os.path.exists(p) and not existed_at_base(p):
        continue
    new = not existed_at_base(p)
    status = "new" if new else "modified"
    if not new:
        desc = MODIFIED.get(p)
    elif p.endswith(".py"):
        desc = docline(p)
    else:
        desc = NEW_NONPY.get(p)
    if not desc:
        missing.append(p)
        continue
    if new and p in DERIVED:
        desc += f"; adapted from {DERIVED[p]}"
    rows.append((p, status, desc))

if missing:
    sys.stderr.write(
        "list_ai_assisted: no stated change for the following files, so the "
        "table would be incomplete. Add them to MODIFIED, NEW_NONPY, or give "
        "the module a docstring:\n  " + "\n  ".join(missing) + "\n")
    sys.exit(1)

rows.sort(key=lambda r: (r[1] != "new", r[0]))
if LISTONLY:
    for p, s, d in rows:
        print(f"{s:8} {p:52} {d}")
    print(f"\n{len(rows)} files "
          f"({sum(1 for r in rows if r[1] == 'new')} new, "
          f"{sum(1 for r in rows if r[1] == 'modified')} modified), "
          f"base {BASE}")
else:
    for p, s, d in rows:
        print(f"\\path{{{p}}} & {s} & {esc(d)} \\\\")
    sys.stderr.write(
        f"{len(rows)} rows "
        f"({sum(1 for r in rows if r[1] == 'new')} new, "
        f"{sum(1 for r in rows if r[1] == 'modified')} modified), "
        f"base {BASE}\n")
PY
rc=$?
rm -f /tmp/.ai_paths.$$
exit $rc
