#!/usr/bin/env python3
"""Emit the lineage appendix: Tables 12c and 13c, plus the lin-str intervals.

Reads only the assembled artifact and the paired intervals, so every number in
the fragment traces to a file rather than to this script. Refuses to emit if
either input is missing or if the two disagree about a cell's lin-str point.

Cells whose |lin-str| does not clear the run-to-run floor are marked, because a
reader should not have to compute that themselves.

  python code/r46_emit_lineage_appendix.py

Output: paper/lineage_appendix.tex
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TREE = ROOT / "results" / "revision" / "T2_2b_lineage_contract"
ASM = TREE / "assembled_lineage_tables.json"
CIS = TREE / "linstr_intervals.json"
OUT = ROOT / "paper" / "lineage_appendix.tex"

# The run-to-run floor. DETERMINISM_MEASURED.json records five cells each run
# twice on one stack at the same seeds; the drifts are +0.0001, +0.0003,
# +0.0006, -0.0004 and -0.0013, so each observation is already the difference
# of two runs. lin-str is the same shape of quantity, one run of each arm, so
# the same floor applies without inflation.
FLOOR = 0.0013
FIELDS = ["econ", "math", "neuro", "physics", "chemistry"]
DISP = {"econ": "economics", "math": "mathematics", "neuro": "neuroscience",
        "physics": "physics", "chemistry": "chemistry"}


def tex(x):
    """Signed number in the paper's own notation."""
    return ("$+$" if x >= 0 else "$-$") + f"{abs(x):.4f}"


def main():
    if not ASM.exists():
        print(f"STOPPING: {ASM} is absent. Run code/r41_assemble_lineage.py.")
        return 2
    if not CIS.exists():
        print(f"STOPPING: {CIS} is absent. Run code/r45_linstr_interval.py; "
              f"without it the lin-str column would be a mean with no "
              f"interval, which this paper does not print.")
        return 2
    asm = json.loads(ASM.read_text(encoding="utf-8"))
    cis = {(c["field"], c["arch"], c["protocol"]): c
           for c in json.loads(CIS.read_text(encoding="utf-8"))["cells"]}

    rows = {}
    for t, blk in asm["tables"].items():
        for f, lst in blk["rows"].items():
            for r in lst:
                arch = "rgcn" if r["cell"].startswith("rgcn") else "gat"
                proto = "prereg" if "prereg" in r["cell"] else "tuned"
                key = (f, arch, proto)
                if key not in cis:
                    print(f"STOPPING: no paired interval for {key}.")
                    return 3
                if abs(cis[key]["lin_minus_str"] - r["lineage_minus_strict"]) > 1e-9:
                    print(f"STOPPING: {key} lin-str disagrees between the "
                          f"assembled tables and the interval file.")
                    return 4
                rows.setdefault(t, []).append((f, arch, proto, r, cis[key]))

    L = []
    L.append("% Generated by code/r46_emit_lineage_appendix.py. Do not edit.")
    L.append(r"\section{The Graph Arm Under the Lineage Contract}")
    L.append(r"\label{app:lineage}")
    L.append("")
    L.append(
        "The strict contract of Appendix~\\ref{app:strict} gives the graph one "
        "advising edge per student. This appendix extends it with two "
        "relations and reruns every cell: advisor to advisor, from the "
        "genealogy's own parent map, and advisor to concept. Nothing is "
        "removed, so the lineage graph is a strict superset and the "
        "lineage-minus-strict column isolates exactly those two relations.")
    L.append("")
    L.append(
        f"That column carries a paired student-level interval, not a bare "
        f"mean. Both arms ran the same ten seeds on the same frozen cohort and "
        f"both ship per-student scores, so the interval is the procedure of "
        f"eq.~(\\ref{{eq:gates}}) with the strict arm in place of the ceiling "
        f"(\\path{{code/r45_linstr_interval.py}}). A dagger marks a cell whose "
        f"lineage-minus-strict magnitude does not clear the {FLOOR:.4f} "
        f"run-to-run floor; those cells are noise and carry no reading.")
    L.append("")

    cap = {"Table 12c": ("Pre-specified budget", "lineage12c"),
           "Table 13c": ("Post hoc symmetric budget", "lineage13c")}
    for t in ("Table 12c", "Table 13c"):
        title, lab = cap[t]
        L.append(r"\begin{table}[t]")
        L.append("\\caption{\\textbf{%s, lineage contract.} Delta against "
                 "M5$'$ with the paired student-level interval, then the "
                 "lineage-minus-strict column with its own paired interval. "
                 "$\\dagger$ does not clear the %.4f run-to-run floor.}"
                 % (title, FLOOR))
        L.append(r"\label{tab:%s}" % lab)
        L.append(r"\scriptsize")
        L.append(r"\setlength{\tabcolsep}{3pt}")
        L.append(r"\begin{tabular}{llrlrlc}")
        L.append(r"\toprule")
        L.append(r"discipline & arch. & $\Delta$M5$'$ & interval & "
                 r"lin$-$str & interval & verdict \\")
        L.append(r"\midrule")
        order = {f: i for i, f in enumerate(FIELDS)}
        for f, arch, proto, r, c in sorted(
                rows[t], key=lambda z: (order[z[0]], z[1])):
            ls = r["lineage_minus_strict"]
            mark = r"$\dagger$" if abs(ls) < FLOOR else ""
            L.append("%s & %s & %s & [%s, %s] & %s%s & [%s, %s] & %s \\\\" % (
                DISP[f], arch.upper(),
                tex(r["delta_vs_M5prime"]), tex(r["ci"][0]), tex(r["ci"][1]),
                tex(ls), mark,
                tex(c["linstr_ci95_paired_student"][0]),
                tex(c["linstr_ci95_paired_student"][1]),
                "exceeds" if r["exceeds"] else "null"))
        L.append(r"\bottomrule")
        L.append(r"\end{tabular}")
        L.append(r"\end{table}")
        L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    n_dag = sum(1 for t in rows for (_, _, _, r, _) in rows[t]
                if abs(r["lineage_minus_strict"]) < FLOOR)
    print(f"[r46] wrote {OUT.name}: 2 tables, 20 rows, {n_dag} marked below "
          f"the {FLOOR} floor")
    print(f"-> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
