#!/usr/bin/env python3
"""Emit the T3.4 TabPFN table as a LaTeX fragment, every value from artifacts.

T3.4 had no table of its own, so the one cell whose verdict rests on a margin
thinner than the run-to-run floor had nowhere to carry a mark. This builds it.

The dagger follows the lineage tables' convention: it marks a cell whose
verdict would change if the point estimate moved by less than the measured
run-to-run floor of 0.0013, so the verdict is not stable under the noise the
project has already measured. Neuroscience is the case here, at +0.0125 with a
student-interval lower bound of -0.0005: the bootstrap covers sampling and the
floor covers run to run, and the two add, so a bound 0.0005 from zero is inside
the combined uncertainty rather than outside it.

Nothing is typed by hand. Run after r33_tabpfn_gpu.py has produced all five
summaries.

  python code/r46_emit_t34_table.py

Output: paper/t34_table.tex, for \\input from the appendix.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "results" / "revision" / "T3_4_tabpfn_gpu"
OUT = ROOT / "paper" / "t34_table.tex"

FIELDS = ["econ", "math", "neuro", "physics", "chemistry"]
# short display names, the same forms the body tables use: at \small with
# eight columns the full names overran the column by 76pt and the CI column
# printed into the margin
DISP = {"econ": "economics", "math": "math", "neuro": "neuro",
        "physics": "physics", "chemistry": "chemistry"}
FLOOR = 0.0013          # DETERMINISM_MEASURED.json, max drift over five cells


def sgn(x, n=4):
    return ("$+$" if x >= 0 else "$-$") + f"{abs(x):.{n}f}"


def main():
    rows, marked = [], []
    for f in FIELDS:
        p = SRC / f / "summary.json"
        if not p.exists():
            print(f"STOPPING: {p} is absent. Run code/r33_tabpfn_gpu.py first.")
            return 2
        d = json.load(open(p, encoding="utf-8"))
        lo, hi = d["student_ci95_vs_M5prime"]
        # A verdict is thin when the distance from the deciding gate to its
        # threshold is smaller than the floor. The deciding gate here is the
        # student-interval lower bound against zero.
        thin = abs(lo) < FLOOR
        if thin:
            marked.append(DISP[f])
        dag = "$^{\\dagger}$" if thin else ""
        verdict = ("exceeds" if d["exceeds_fair"] else "null") + dag
        over = "yes" if d["exceeds_pretraining_limit"] else "no"
        rows.append(
            f"{DISP[f]} & {d['train_rows_used']:,} & {over} & "
            f"{d['tabpfn_mean_auc_pr']:.4f} & {d['M5prime_mean']:.4f} & "
            f"{sgn(d['delta_vs_M5prime'])} & {sgn(lo)}, {sgn(hi)} & "
            + verdict + r" \\")

    n_over = sum(1 for f in FIELDS
                 if json.load(open(SRC / f / "summary.json",
                                   encoding="utf-8"))["exceeds_pretraining_limit"])
    body = "\n".join(rows)
    tex = f"""% Generated by code/r46_emit_t34_table.py. Do not edit by hand.
\\begin{{table}}[t]
\\caption{{\\textbf{{TabPFN without the CPU context handicap.}} Ten seeds per
discipline, varied through the model's ensemble permutations rather than
through a training subsample. The training rows column is the full modeled
training split; {({1: 'one', 2: 'two', 3: 'three', 4: 'four'}.get(n_over, str(n_over)))} of five disciplines exceed TabPFN v2's stated
pretraining limit of 10{{,}}000 rows, which is a caveat on the model's operating
range and not on the protocol. No discipline passes all three gates of
eq.~(\\ref{{eq:gates}}), so every verdict is null, but four of the five means sit
above M5$'$. $^{{\\dagger}}$ marks a verdict whose deciding gate clears its
threshold by less than the measured run-to-run floor of {FLOOR}, so the verdict
is not stable under noise the project has already measured; the bootstrap
covers sampling and the floor covers run to run, and the two add. From
\\protect\\path{{results/revision/T3_4_tabpfn_gpu/}}.}}
\\label{{tab:tabpfngpu}}
\\scriptsize
\\setlength{{\\tabcolsep}}{{2.5pt}}
\\begin{{tabular}}{{lrlrrrrl}}
\\toprule
discipline & train rows & over limit & TabPFN & M5$'$ & $\\Delta$ vs M5$'$ &
95\\% CI (student) & verdict \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    OUT.write_text(tex, encoding="utf-8")
    print(f"[r46] {len(rows)} rows, {n_over} over the pretraining limit "
          f"({', '.join(DISP[f] for f in FIELDS if json.load(open(SRC / f / 'summary.json', encoding='utf-8'))['exceeds_pretraining_limit'])})")
    print(f"[r46] dagger on {len(marked)}: {', '.join(marked) or 'none'}")
    print(f"-> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
