#!/usr/bin/env python3
"""T4.x: emit the innovation-premium appendix from the artifact, not by hand.

The premium moves out of Table 6 and into an appendix, reported as an
exploratory finding. Every coefficient, standard error and p-value below is read
from results/revision/T2_9_premium_specs/premium_specs.json, which r21 built
from the five frozen e6_innovation_premium.json files. Nothing here is typed.

What the appendix may say is limited to what the repository documents. It states
that the designation of specification 3 as primary is not recorded as
pre-specified anywhere, and it states what specification 4 does to the two
disciplines whose reading it changes most. It does not argue that specification
3 is the right choice, because no document in this repository makes that
argument and inventing one would be worse than reporting the gap.

Output: paper/premium_appendix.tex, input by main.tex.

  python code/r52_emit_premium_appendix.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "results" / "revision" / "T2_9_premium_specs" / "premium_specs.json"
OUT = ROOT / "paper" / "premium_appendix.tex"
SPECS = ["1_raw", "2_controls", "3_controls_FE", "4_structural_FE"]
NAME = {"econ": "economics", "math": "math", "neuro": "neuro",
        "physics": "physics", "chemistry": "chemistry"}
ORDER = ["econ", "math", "neuro", "physics", "chemistry"]


def coef(c):
    s = "$+$" if c >= 0 else "$-$"
    return f"{s}{abs(c):.4f}"


def pval(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def main():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    F = d["fields"]
    n_changed = d["n_changed"]
    changed = d["disciplines_whose_reading_changes_between_spec3_and_spec4"]

    ne3, ne4 = F["neuro"]["3_controls_FE"], F["neuro"]["4_structural_FE"]
    ec3, ec4 = F["econ"]["3_controls_FE"], F["econ"]["4_structural_FE"]

    rows = []
    for f in ORDER:
        cells = []
        for s in SPECS:
            c = F[f][s]
            cells += [coef(c["coef"]), pval(c["p"])]
        rows.append(f"{NAME[f]} & " + " & ".join(cells) + r" \\")

    body = "\n".join(rows)
    prose = (
        "\\section{The Innovation Premium}\n"
        "\\label{app:premium}\n"
        "\n"
        "The premium is the coefficient on divergence from the advisor in a "
        "regression of the student's late-window citation percentile, with "
        "advisor-clustered standard errors. It is reported here rather than in "
        "the body, and as an exploratory finding, for one reason that is a fact "
        "about this repository rather than a judgement about the estimate: "
        "the designation of specification 3 as the primary reading is not "
        "documented as pre-specified in the repository or in the paper. No "
        "pre-specification record fixes it.\n"
        "\n"
        "Table~\\ref{tab:premiumspecs} gives all four specifications in all five "
        "disciplines. Specifications 1 to 3 estimate one regressor, "
        "concept-space divergence, at three levels of adjustment. Specification "
        "4 keeps specification 3's controls and fixed effects and substitutes a "
        "different regressor, structural Node2Vec~\\cite{grover2016node2vec} "
        "divergence "
        "(\\protect\\path{e6_innovation_premium.py:68-78}). The reading changes "
        f"between the two in {n_changed} of the five disciplines "
        f"({', '.join(NAME[c] for c in changed)}).\n"
        "\n"
        "Two of those changes are large enough to state in full. Neuroscience "
        f"reverses sign, from {coef(ne3['coef'])} at $p$ {pval(ne3['p'])} under "
        f"specification 3 to {coef(ne4['coef'])} at $p$ {pval(ne4['p'])} under "
        "specification 4. Economics moves from "
        f"{coef(ec3['coef'])} at $p$ {pval(ec3['p'])}, which the frozen run "
        f"reads as no effect, to {coef(ec4['coef'])} at $p$ {pval(ec4['p'])}.\n"
        "\n"
        "The frozen e6 readings are unchanged and retained. What is superseded "
        "is their status in the paper, from a body-table column to an "
        "exploratory appendix result; the values themselves stand as the frozen "
        "run produced them, and Table~\\ref{tab:premiumspecs} prints them "
        "beside the three specifications the body never quoted.\n"
    )

    tex = (
        "% GENERATED by code/r52_emit_premium_appendix.py. Do not edit by hand.\n"
        "% Source: results/revision/T2_9_premium_specs/premium_specs.json\n"
        + prose +
        "\n"
        "\\begin{table*}[t]\n"
        "\\caption{\\textbf{Innovation premium, all four specifications.} "
        "Divergence coefficient on the late-window citation percentile, "
        "advisor-clustered standard errors, from the five frozen "
        "\\protect\\path{e6_innovation_premium.json} files collected by "
        "\\protect\\path{code/r21_premium_specs.py}. Columns 1 to 3 are a nested "
        "ladder on concept-space divergence; column 4 substitutes structural "
        "Node2Vec divergence under specification 3's controls and fixed effects, "
        "so the rule marks where the regressor changes rather than where the "
        "adjustment tightens. Emitted by "
        "\\protect\\path{code/r52_emit_premium_appendix.py}; no value is typed.}\n"
        "\\label{tab:premiumspecs}\n"
        "\\small\n"
        "\\begin{tabular}{lrrrrrr|rr}\n"
        "\\toprule\n"
        "& \\multicolumn{6}{c|}{regressor \\texttt{divergence}, concept space}\n"
        "& \\multicolumn{2}{c}{regressor \\texttt{n2v\\_divergence}, structural} \\\\\n"
        "\\cmidrule(lr){2-7}\\cmidrule(lr){8-9}\n"
        "& \\multicolumn{2}{c}{1 raw} & \\multicolumn{2}{c}{2 controls}\n"
        "& \\multicolumn{2}{c|}{3 controls + FE} & \\multicolumn{2}{c}{4 controls + FE} \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}\n"
        "discipline & coef & $p$ & coef & $p$ & coef & $p$ & coef & $p$ \\\\\n"
        "\\midrule\n"
        + body + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table*}\n"
    )
    OUT.write_text(tex, encoding="utf-8")
    print(f"[r52] {len(rows)} disciplines x {len(SPECS)} specifications -> {OUT}")
    print(f"[r52] reading changes between 3 and 4 in {n_changed}: "
          f"{', '.join(changed)}")


if __name__ == "__main__":
    main()
