#!/usr/bin/env python3
"""Emit the compact official-verdict table as paper/official_verdicts.tex.

One row per discipline over the strict-contract tree, the canonical protocol:
cells run, cells exceeding eq. (2) against M5', and the largest gap's cell with
its paired student-level interval. Every value is read from
assembled_tables.json; the eight-cell detail stays in Table tab:gnn and the
full grid in Appendix app:strict.

  python code/r60_emit_official_verdicts.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "code"))
from r28_assemble_tables import FIELDS, TREE  # noqa: E402

OUT = ROOT / "paper" / "official_verdicts.tex"
DISP = {"econ": "economics", "math": "mathematics", "neuro": "neuroscience",
        "physics": "physics", "chemistry": "chemistry"}
ARCH = {"HGT": "HGT", "HGT tuned": "HGT tuned", "RGCN": "RGCN", "GAT": "GAT",
        "RGCN symmetric": "RGCN sym.", "GAT symmetric": "GAT sym."}


def num(x):
    s = f"{abs(x):.4f}"
    return ("$+$" if x >= 0 else "$-$") + s


def main():
    data = json.loads((TREE / "assembled_tables.json").read_text(encoding="utf-8"))
    rows = []
    total_cells = total_exceed = 0
    for f in FIELDS:
        cells = []
        for tab in data["tables"].values():
            cells.extend(tab["rows"].get(f, []))
        n = len(cells)
        ex = [c for c in cells if c["exceeds"]]
        best = max(cells, key=lambda c: c["delta_vs_M5prime"])
        lo, hi = best["ci"]
        total_cells += n
        total_exceed += len(ex)
        rows.append(
            f"{DISP[f]} & {n} & {len(ex)} & "
            f"{ARCH.get(best['row'], best['row'])} & "
            f"{num(best['delta_vs_M5prime'])} & [{num(lo)}, {num(hi)}] \\\\")
    if total_cells != 39 or total_exceed != 5:
        raise SystemExit(f"r60: expected 39 cells and 5 exceeding, found "
                         f"{total_cells} and {total_exceed}; refusing to emit")
    tex = r"""% GENERATED by code/r60_emit_official_verdicts.py. Do not edit by hand.
% Source: the strict-contract assembled cells (assembled_tables.json).
\begin{table}[t]
\caption{\textbf{The official verdicts, canonical protocol.} Strict contract,
all cells per discipline over both budgets, judged by the three gates of
eq.~(\ref{eq:gates}) against M5$'$. The largest gap per discipline is shown
with its paired student-level interval; Table~\ref{tab:gnn} gives the eight
cells the readings turn on and Appendix~\ref{app:strict} every value. From
\protect\path{results/revision/T2_1_strict_contract/}.}
\label{tab:official}
\small
\setlength{\tabcolsep}{2.4pt}
\begin{tabular}{lrrlll}
\toprule
discipline & cells & exceed & largest gap & $\Delta$ vs M5$'$ & 95\% CI (student) \\
\midrule
__ROWS__
\bottomrule
\end{tabular}
\end{table}
"""
    OUT.write_text(tex.replace("__ROWS__", "\n".join(rows)),
                   encoding="utf-8", newline="\n")
    print(f"  wrote {OUT}")
    print(f"  {total_cells} cells, {total_exceed} exceed")


if __name__ == "__main__":
    sys.exit(main())
